### ISSUE TITLE
Introduce a README.md 

### ISSUE THREAD

**Issue by vybhav72954** [nickrod518/PowerShell-Scripts#14]
Scripts here are wonderful but mostly useless for a noob PowerShell enthusiast.

I believe having a markdown that explains the basic working of PowerShell Scripts or how to get started with them and implement them in your system can work wonders.

**Comment by nickrod518** [comment]
Hi @vybhav72954 !

You are absolutely right, these scripts are not going to be extremely useful for someone new to PowerShell. The intent was if a person had an obscure PowerShell scripting need they could search this repo for example code to start with. I would love it if I had more time to add instructions and more scripts I have written to this project, but I simply don't. Since this is an open source project, you are welcome to contribute with a pull request, if you wish.

Thanks,
Nick
